### ISSUE TITLE
Could not resolve './nx.android-arm64.node'

### ISSUE THREAD

**Issue by kespeart** [NiklasPor/nx-remotecache-custom#25]
## Problem

When I install `@nx/workspace` in the root of my Monorepo repository I get the below error. There a several packages in the Monorepo but only the packages that uses `nx-remotecache-custom` fails to build because of the below error. Has anyone experienced a similar issue?

### Error
```
[!] Error: Could not resolve './nx.android-arm64.node' from ./nx.android-arm64.node?commonjs-external
Error: Could not resolve './nx.android-arm64.node' from ./nx.android-arm64.node?commonjs-external
    at error (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:151:30)
    at ModuleLoader.handleResolveId (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19817:24)
    at /usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19766:22
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19764:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19740:9)
    at async Promise.all (index 34)
    at ModuleLoader.fetchStaticDependencies (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19764:34)
    at async Promise.all (index 0)
npm ERR! Lifecycle script `build:prod` failed with error: 
npm ERR! Error: command failed 
```
### Image
<img width="1097" alt="Screen Shot 2023-10-04 at 1 06 42 PM" src="https://github.com/NiklasPor/nx-remotecache-custom/assets/9921620/0fd9e7d2-011a-4df7-b8bc-b824ef162dda">

There is also another variant of this issue which is shown below

```
 [!] Error: Could not resolve './nx.darwin-x64.node' from ./nx.darwin-x64.node?commonjs-external
 Error: Could not resolve './nx.darwin-x64.node' from ./nx.darwin-x64.node?commonjs-external
     at error (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:151:30)
     at ModuleLoader.handleResolveId (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19817:24)
     at /usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19766:22
     at async Promise.all (index 0)
     at ModuleLoader.fetchStaticDependencies (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19764:34)
     at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19740:9)
    at async Promise.all (index 46)
     at ModuleLoader.fetchStaticDependencies (/usr/src/libs/node_modules/rollup/dist/shared/rollup.js:19764:34)
     at async Promise.all (index 0)
 npm ERR! Lifecycle script `build:prod` failed with error: 
 npm ERR! Error: command failed 
```
### Versions
We run the build in a docket container that uses node 16 and NPM 9.
@nx/workspace@16.5.3
nx-remotecache-custom@4.2.1

**Comment by escaton** [comment]
Does anybody know, why this package depends on `@nx/workspace` for `@nx/workspace/tasks-runners/default`, while there is the same runner in the core `nx` package?

**Comment by NiklasPor** [comment]
@escaton I wrote it and it's historical. I can update the implementation, if there are no other implications 👍

**Comment by kespeart** [comment]
Someone on my team was able to resolve this issue. The problem is that we were using rollup. While the `require` statements for the different platforms are conditional i.e logically `./nx.darwin-x64.node` will only be imported on macOS systems. Rollup does not respect this, therefore when rollup parses JS looking for `require` statements it will try to process each `require` statement it finds, irrespective of the fact that the statement is bounded by conditional logic.

Lucky for us, we were able to move to Babel for bundling
